apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-nodered
spec:
  capacity:
    storage: {{ .Values.nodered.storageSize }}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: /mnt/data/nodered  # Replace with a valid path on your node